// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {service} from '../models';

export function BackendHealth(arg1:string):Promise<{[key: string]: any}>;

export function CopyEnvExample():Promise<{[key: string]: string}>;

export function CreateTag(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<{[key: string]: string}>;

export function DeleteEnvVar(arg1:string):Promise<void>;

export function GetEnvStatus():Promise<model.EnvStatus>;

export function GetMigrationStatus():Promise<model.MigrationStatus>;

export function GetNotices():Promise<Array<model.Notice>>;

export function GetPrerequisites():Promise<Array<model.Prerequisite>>;

export function GetProtoStatus():Promise<model.ProtoStatus>;

export function GitHubDisconnect():Promise<service.Permissions>;

export function GitHubGetStatus():Promise<service.Permissions>;

export function GitHubPollAuth():Promise<service.Permissions>;

export function GitHubRefreshTeams():Promise<service.Permissions>;

export function GitHubStartDeviceFlow():Promise<service.DeviceFlowResponse>;

export function ListBackendServices():Promise<Array<model.BackendService>>;

export function ListProjectDependencies(arg1:string):Promise<Array<model.Dependency>>;

export function ListProjects():Promise<Array<model.Project>>;

export function ListServices():Promise<Array<model.Service>>;

export function ListTags(arg1:string):Promise<{[key: string]: any}>;

export function ProjectClone(arg1:string):Promise<{[key: string]: string}>;

export function ProjectOpen(arg1:string):Promise<{[key: string]: string}>;

export function ProjectUpdate(arg1:string):Promise<{[key: string]: string}>;

export function RunMigrationDown():Promise<{[key: string]: string}>;

export function RunMigrationUp():Promise<{[key: string]: string}>;

export function StartAllServices():Promise<{[key: string]: string}>;

export function StartBackendGroup(arg1:string):Promise<{[key: string]: string}>;

export function StartBackendLogsStream(arg1:string):Promise<void>;

export function StartBackendService(arg1:string):Promise<{[key: string]: string}>;

export function StartBulkProjectStream(arg1:string):Promise<void>;

export function StartMigrationStream(arg1:string):Promise<void>;

export function StartProjectStream(arg1:string,arg2:string):Promise<void>;

export function StartProtoStream():Promise<void>;

export function StartService(arg1:string):Promise<{[key: string]: string}>;

export function StartServiceLogsStream(arg1:string):Promise<void>;

export function Status():Promise<{[key: string]: any}>;

export function StopAllServices():Promise<{[key: string]: string}>;

export function StopBackendGroup(arg1:string):Promise<{[key: string]: string}>;

export function StopBackendLogsStream(arg1:string):Promise<void>;

export function StopBackendService(arg1:string):Promise<{[key: string]: string}>;

export function StopBulkProjectStream(arg1:string):Promise<void>;

export function StopMigrationStream(arg1:string):Promise<void>;

export function StopProjectStream(arg1:string,arg2:string):Promise<void>;

export function StopProtoStream():Promise<void>;

export function StopService(arg1:string):Promise<{[key: string]: string}>;

export function StopServiceLogsStream(arg1:string):Promise<void>;

export function SubmoduleSync(arg1:string):Promise<{[key: string]: string}>;

export function SubmoduleSyncStatus():Promise<{[key: string]: any}>;

export function UpdateEnvVar(arg1:string,arg2:string):Promise<void>;

export function ValidateEnv():Promise<{[key: string]: any}>;
