// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackendHealth(arg1) {
  return window['go']['main']['App']['BackendHealth'](arg1);
}

export function CopyEnvExample() {
  return window['go']['main']['App']['CopyEnvExample']();
}

export function CreateTag(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateTag'](arg1, arg2, arg3, arg4);
}

export function DeleteEnvVar(arg1) {
  return window['go']['main']['App']['DeleteEnvVar'](arg1);
}

export function GetEnvStatus() {
  return window['go']['main']['App']['GetEnvStatus']();
}

export function GetMigrationStatus() {
  return window['go']['main']['App']['GetMigrationStatus']();
}

export function GetNotices() {
  return window['go']['main']['App']['GetNotices']();
}

export function GetPrerequisites() {
  return window['go']['main']['App']['GetPrerequisites']();
}

export function GetProtoStatus() {
  return window['go']['main']['App']['GetProtoStatus']();
}

export function ListBackendServices() {
  return window['go']['main']['App']['ListBackendServices']();
}

export function ListProjectDependencies(arg1) {
  return window['go']['main']['App']['ListProjectDependencies'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListServices() {
  return window['go']['main']['App']['ListServices']();
}

export function ListTags(arg1) {
  return window['go']['main']['App']['ListTags'](arg1);
}

export function ProjectClone(arg1) {
  return window['go']['main']['App']['ProjectClone'](arg1);
}

export function ProjectOpen(arg1) {
  return window['go']['main']['App']['ProjectOpen'](arg1);
}

export function ProjectUpdate(arg1) {
  return window['go']['main']['App']['ProjectUpdate'](arg1);
}

export function RunMigrationDown() {
  return window['go']['main']['App']['RunMigrationDown']();
}

export function RunMigrationUp() {
  return window['go']['main']['App']['RunMigrationUp']();
}

export function StartAllServices() {
  return window['go']['main']['App']['StartAllServices']();
}

export function StartBackendGroup(arg1) {
  return window['go']['main']['App']['StartBackendGroup'](arg1);
}

export function StartBackendLogsStream(arg1) {
  return window['go']['main']['App']['StartBackendLogsStream'](arg1);
}

export function StartBackendService(arg1) {
  return window['go']['main']['App']['StartBackendService'](arg1);
}

export function StartBulkProjectStream(arg1) {
  return window['go']['main']['App']['StartBulkProjectStream'](arg1);
}

export function StartMigrationStream(arg1) {
  return window['go']['main']['App']['StartMigrationStream'](arg1);
}

export function StartProjectStream(arg1, arg2) {
  return window['go']['main']['App']['StartProjectStream'](arg1, arg2);
}

export function StartProtoStream() {
  return window['go']['main']['App']['StartProtoStream']();
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StartServiceLogsStream(arg1) {
  return window['go']['main']['App']['StartServiceLogsStream'](arg1);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function StopAllServices() {
  return window['go']['main']['App']['StopAllServices']();
}

export function StopBackendGroup(arg1) {
  return window['go']['main']['App']['StopBackendGroup'](arg1);
}

export function StopBackendLogsStream(arg1) {
  return window['go']['main']['App']['StopBackendLogsStream'](arg1);
}

export function StopBackendService(arg1) {
  return window['go']['main']['App']['StopBackendService'](arg1);
}

export function StopBulkProjectStream(arg1) {
  return window['go']['main']['App']['StopBulkProjectStream'](arg1);
}

export function StopMigrationStream(arg1) {
  return window['go']['main']['App']['StopMigrationStream'](arg1);
}

export function StopProjectStream(arg1, arg2) {
  return window['go']['main']['App']['StopProjectStream'](arg1, arg2);
}

export function StopProtoStream() {
  return window['go']['main']['App']['StopProtoStream']();
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}

export function StopServiceLogsStream(arg1) {
  return window['go']['main']['App']['StopServiceLogsStream'](arg1);
}

export function SubmoduleSync(arg1) {
  return window['go']['main']['App']['SubmoduleSync'](arg1);
}

export function SubmoduleSyncStatus() {
  return window['go']['main']['App']['SubmoduleSyncStatus']();
}

export function UpdateEnvVar(arg1, arg2) {
  return window['go']['main']['App']['UpdateEnvVar'](arg1, arg2);
}

export function ValidateEnv() {
  return window['go']['main']['App']['ValidateEnv']();
}
